### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by paf31**
@garyb @joneshf Would you please review this?

### CODE REVIEW

**Comment by garyb** [comment]
Nice! I'd probably replace the current `README.md` with this too, seems a more useful thing to be greeted with than the npm/bower instructions to me.

**Comment by paf31** [comment]
Oh right. I was going to update that to include a link to the module docs, like in the other repos. I'll do that now.

**Comment by garyb** [comment]
I think I just did that so the travis badge could be shown upfront for the other ones that are split that way, now we have the fancy documentation I think that's much better :)

**Comment by paf31** [comment]
Looks nice :)

http://functorial.com/psc-pages/docs/Data/Exists/index.html

**Pull request merged**
